services:
  quallm-backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/app/backend
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./backend
    #       target: /app/backend
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - backend.env
    # depends_on:
    #   - redis

  quallm-frontend:
    build: ./frontend
    tty: true
    volumes:
      - ./frontend:/app/frontend
    # develop:
    #   watch:
    #     - action: sync+restart
    
    #       path: ./frontend
    #       target: /app/frontend
    ports:
      - "8501:8501"
    command: streamlit run frontend/app.py

# todo: 非同期タスク処理できるようにする
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  # celery_worker:
  #   build: .
  #   command: celery -A backend.tasks.celery_app worker --loglevel=info
  #   depends_on:
  #     - redis